[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rich_logger"
version = "0.1.0"
description = "My custom loguru logger"
dependencies = [
    "loguru"
]

[tool.setuptools.packages.find]
where = ["src"]
